version: '3.4'

networks:
  farm-manager:
    driver: bridge 

services:
  farm-manager-service:
    image: ${REGISTRY:-davidberschauer}/farm-manager:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      - "farm-manager-db"
    container_name: farm-manager-service
    ports:
      - "5009:80"
      - "5001:443"
    build:
      context: .
      dockerfile: FarmManager/Server/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Farm_Manager
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp_2.pfx
      - ASPNETCORE_ENVIRONMENT=Development
      - FarmsConnectionString=host=farm-manager-db;port=5432;database=farm-manager;username=postgres;password=postgres;Pooling=true;
    volumes:
      - ${HOME}/.aspnet/https:/https/ 
    networks:
      - farm-manager

  farm-manager-db:
    image: postgres:latest
    container_name: farm-manager-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - farm-manager

volumes:
  customer_data:

